[font]
size = 12.0
normal.family = "MonaspiceKr Nerd Font"
bold.family = "MonaspiceKr Nerd Font"
italic.family = "MonaspiceKr Nerd Font"
bold_italic.family = "MonaspiceKr Nerd Font"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.25
blur = true

[window.padding]
x = 18
y = 16

[general]
live_config_reload = true
