dictionaries = [
    "de",
    "hr_hr",
    "en_us",
]
words = [
    "Chatbot",
    "Dotmarks",
    "Unslop",
    "MCP",
    "activecampaign",
    "aftersales",
    "analyse",
    "apikey",
    "arraybuffer",
    "atuin",
    "autoloading",
    "autoprefixer",
    "autoresponders",
    "aweber",
    "axios",
    "bantr",
    "birdsend",
    "bla",
    "btop",
    "campaignrefinery",
    "cli",
    "commenters",
    "constantcontactnew",
    "convertkit",
    "creo",
    "creolab",
    "demio",
    "efd",
    "efit",
    "egoiv",
    "encrypter",
    "everwebinar",
    "eza",
    "familyname",
    "ffu",
    "fillable",
    "flashspace",
    "fluentcrm",
    "fzf",
    "getresponse",
    "ghostty",
    "gotowebinar",
    "helpdesk",
    "homebrew",
    "hubspot",
    "icontact",
    "infusionsoft",
    "intelephense",
    "karabiner",
    "keap",
    "klicktipp",
    "kourses",
    "laravel",
    "leaderboard",
    "leaderboards",
    "leadlovers",
    "livewire",
    "madmimi",
    "mailchimp",
    "mailpoet",
    "matija",
    "mautic",
    "mdm",
    "memberpress",
    "mins",
    "monolog",
    "moosend",
    "mountpoint",
    "multibrand",
    "neofetch",
    "neovim",
    "nevco",
    "nfd",
    "novcic",
    "nvim",
    "nvm",
    "ontraport",
    "opc",
    "opd",
    "opm",
    "optimizecheckouts",
    "optimizementor",
    "optimizepress",
    "optimizesubscriber",
    "optin",
    "opu",
    "opui",
    "phptools",
    "pnpm",
    "quentn",
    "raylib",
    "requalify",
    "ripgrep",
    "rollup",
    "rtp",
    "samcart",
    "scriptable",
    "sendfox",
    "sendgrid",
    "sendinblue",
    "sendlane",
    "sendreach",
    "sendy",
    "sketchybar",
    "spatie",
    "spotify",
    "starship",
    "statamic",
    "strahija",
    "superadmin",
    "thrivecart",
    "tmux",
    "tmuxinator",
    "ttl",
    "umami",
    "vite",
    "vscode",
    "vue's",
    "webinarjam",
    "wezterm",
    "winamp",
    "wishlist",
    "yazi",
    "zapier",
    "zellij",
    "zimsko",
    "zoomnew",
    "zoxide",
]
