words = [
    "analyse",
    "autoprefixer",
    "autoresponders",
    "axios",
    "fillable",
    "homebrew",
    "laravel",
    "livewire",
    "monolog",
    "opd",
    "optin",
    "spatie",
    "vite",
]
