words = [
    "activecampaign",
    "analyse",
    "apikey",
    "atuin",
    "autoloading",
    "autoprefixer",
    "autoresponders",
    "aweber",
    "axios",
    "birdsend",
    "btop",
    "campaignrefinery",
    "constantcontactnew",
    "convertkit",
    "creo",
    "demio",
    "egoiv",
    "encrypter",
    "everwebinar",
    "fillable",
    "flashspace",
    "fluentcrm",
    "getresponse",
    "ghostty",
    "gotowebinar",
    "helpdesk",
    "homebrew",
    "hubspot",
    "icontact",
    "infusionsoft",
    "intelephense",
    "karabiner",
    "keap",
    "klicktipp",
    "kourses",
    "laravel",
    "leadlovers",
    "livewire",
    "madmimi",
    "mailchimp",
    "mailpoet",
    "matija",
    "mautic",
    "memberpress",
    "monolog",
    "moosend",
    "mountpoint",
    "neofetch",
    "nevco",
    "novcic",
    "nvim",
    "ontraport",
    "opc",
    "opd",
    "opm",
    "optimizementor",
    "optimizepress",
    "optin",
    "opui",
    "phptools",
    "quentn",
    "ripgrep",
    "sendfox",
    "sendgrid",
    "sendinblue",
    "sendlane",
    "sendreach",
    "sendy",
    "sketchybar",
    "spatie",
    "starship",
    "statamic",
    "tmux",
    "tmuxinator",
    "ttl",
    "umami",
    "vite",
    "vscode",
    "vue's",
    "webinarjam",
    "wezterm",
    "winamp",
    "wishlist",
    "zapier",
    "zellij",
    "zoomnew",
]
