style = "full"      # Can be "full" or "compact"
enter_accept = true

[dotfiles]
enabled = true

[stats]

[sync]
# Enable sync v2 by default
# This ensures that sync v2 is enabled for new installs only
# In a later release it will become the default across the board
records = true
