return {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
        plugins = {
            presets = {
                operators = true,
                motions = true,
                text_objects = true,
                windows = true,
                nav = true,
                z = true,
                g = true,
            },
        },
    },
    config = function(_, opts)
        local wk = require("which-key")
        wk.setup(opts)
        wk.add({
            { "<leader>f", group = "find" },
            { "<leader>ff", desc = "Find Files" },
            { "<leader>fg", desc = "Live Grep" },
            { "<leader>fb", desc = "Buffers" },
            { "<leader>fr", desc = "Recent Files" },
            { "<leader>fs", desc = "Search Buffer" },
            { "<leader>fp", desc = "Git Files" },
            { "<leader>fe", desc = "Resume Picker" },
            { "<leader>fd", desc = "Diagnostics" },
            { "<leader>b", group = "buffer" },
            { "<leader>bb", desc = "Alternate Buffer" },
            { "<leader>bn", desc = "Next Buffer" },
            { "<leader>bp", desc = "Previous Buffer" },
            { "<leader>bd", desc = "Delete Buffer" },
            { "<leader>g", group = "git" },
            { "<leader>gg", desc = "Git Status" },
            { "<leader>gh", desc = "Buffer History" },
            { "<leader>gl", desc = "Git Commits" },
            { "<leader>gb", desc = "Blame Line" },
            { "<leader>gB", desc = "Toggle Blame" },
            { "<leader>e", group = "diagnostics" },
            { "<leader>ee", desc = "Diagnostics" },
            { "<leader>en", desc = "Next Diagnostic" },
            { "<leader>ep", desc = "Prev Diagnostic" },
            { "<leader>t", group = "toggle" },
            { "<leader>tg", desc = "Toggle Tab Bar" },
            { "<leader>s", group = "settings" },
            { "<leader>p", group = "projects" },
            { "<leader>pp", desc = "Switch Project" },
            { "<leader>pr", desc = "Recent Projects" },
            { "<leader>pf", desc = "Project Files" },
            { "<leader>po", desc = "Project Root" },
            { "<leader>h", group = "hunks" },
            { "<leader>hs", desc = "Stage Hunk" },
            { "<leader>hu", desc = "Undo Stage Hunk" },
            { "<leader>hr", desc = "Reset Hunk" },
            { "<leader>hp", desc = "Preview Hunk" },
            { "<leader>hb", desc = "Blame Line" },
            { "<leader>hB", desc = "Toggle Blame" },
            { "<leader>x", group = "extras" },
            { "<leader>xe", desc = "Emmet Wrap" },
            { "<leader>l", group = "lsp" },
            { "<leader>lf", desc = "Format Buffer" },
            { "]m", desc = "Next Function", mode = { "n", "x", "o" } },
            { "[m", desc = "Prev Function", mode = { "n", "x", "o" } },
            { "]a", desc = "Swap Next Parameter", mode = { "n", "x", "o" } },
            { "[a", desc = "Swap Prev Parameter", mode = { "n", "x", "o" } },
            { "a", group = "around", mode = { "o", "x" } },
            { "i", group = "inside", mode = { "o", "x" } },
        })
    end,
}
